### ISSUE TITLE
gets blocked when using ublock in firefox

### ISSUE THREAD

**Issue by of-me-is** [Sytorex-pro/UltimateClosedCaptions#4]
The "cc" button disappears when ublock is on in Firefox browser. When ublock is tuned off, the button is visible again. In Chrome there is no such issue. 

Maybe it's possible to whitelist the page element by name, but I can't find the name/path.

**Comment by Salutations45** [comment]
I can't reproduce this issue.

You probably have a custom filter blocking the extension.

Is only the button blocked or the complete extension (can you see captions) ?

**Comment by of-me-is** [comment]
it was a custom filter, you're right! sorry, didn't occur to me to check because i don't remember adding any for twitch, but it was this one and apparently it's the overlay one

> ||supervisor.ext-twitch.tv/supervisor/v1/index.html$subdocument

i removed it and the buttons are all there. thanks again!
